export const auto_ri_address = [
    { value: '1st Stop Auto Sales', label: '1st Stop Auto Sales - 41A Reservoir Avenue,Providence,RI,02907' },
    { value: '24/7 Auto Sales', label: '24/7 Auto Sales - 626 Main Street, Pawtucket, RI 02860' },
    { value: '44 Auto Mall Sales, Inc.', label: '44 Auto Mall Sales, Inc. - 270-280 Putnam Pike,Smithfield,RI,02917' },
    { value: 'A & D Auto Sales & Service Center, Inc.', label: 'A & D Auto Sales & Service Center, Inc. - 4 Log Road ,Smithfield,RI,02917' },
    { value: 'A&G Auto Sales & Recon., Inc.', label: 'A&G Auto Sales & Recon., Inc. - 10 Humbert Street,North Providence ,RI,02911' },
    { value: 'A&R Auto Sales, Inc.', label: 'A&R Auto Sales, Inc. - 1165 Warwick Avenue,Warwick,RI,02888' },
    { value: 'A&T Auto Sales, LLC "Main"', label: 'A&T Auto Sales, LLC "Main" - 195R JP Murphy Highway,West Warwick,RI,02893' },
    { value: 'AAA Car Buying Service', label: 'AAA Car Buying Service - 160 Royal Little Drive,Providence,RI,02904' },
    { value: 'ABC Auto Sales, LLC', label: 'ABC Auto Sales, LLC - 44D Terry Lane,Chepachet,RI,02814' },
    { value: 'Academy Cars, LLC', label: 'Academy Cars, LLC - 239 Academy Avenue,Providence ,RI,02908' },
    { value: 'Accurate Automotive Sales & Service', label: 'Accurate Automotive Sales & Service - 939 Newport Avenue, Pawtucket, RI 02908' },
    { value: 'Adrenaline Rush Motorsports', label: 'Adrenaline Rush Motorsports - 1823 New London Turnpike, West Warwick, RI 02893' },
    { value: 'Advanced Auto Sales, Inc.', label: 'Advanced Auto Sales, Inc. - 116 Kersey Road,Peacedale ,RI,02883' },
    { value: 'Advanced Remarketing Services, Inc.', label: 'Advanced Remarketing Services, Inc. - 116 Johnnycake Hill,Middletown,RI,02842' },
    { value: 'Affordable Auto Sales, Inc.', label: 'Affordable Auto Sales, Inc. - 96 Evergreen Avenue,Warwick,RI,02888' },
    { value: 'Agility Auto Sales', label: 'Agility Auto Sales - 2381 Post Road,Warwick,RI,02886' },
    { value: 'Al Montecalvo’s Auto Clinic, Inc.', label: 'Al Montecalvo’s Auto Clinic, Inc. - 650 Hartford Pike Rte 101,North Scituate,RI,02857' },
    { value: 'Alfredo’s Auto Sales & Body', label: 'Alfredo’s Auto Sales & Body - 1 Peter Road,Bristol ,RI,02809' },
    { value: 'Alpine Auto Sales', label: 'Alpine Auto Sales - 416 West Fountain Street,Providence ,RI,02903' },
    { value: 'American Auto Sales & Auto Body, Inc.', label: 'American Auto Sales & Auto Body, Inc. - 448 Dyer Avenue,Cranston,RI,02920' },
    { value: 'American Performance Auto Sales, Inc.', label: 'American Performance Auto Sales, Inc. - 1006 Cranston Street,Cranston,RI,02920' },
    { value: 'Anchor Nissan', label: 'Anchor Nissan - 1041 Eddie Dowling Hwy,North Smithfield,RI,02896' },
    { value: 'Anchor Subaru, LLC', label: 'Anchor Subaru, LLC - 949 Eddie Dowling Highway, North Smithfield,RI,02896' },
    { value: 'Angelo Padula & Son Auto Sales & Used Auto Parts', label: 'Angelo Padula & Son Auto Sales & Used Auto Parts - Pole 2, Canna Street,West Warwick ,RI,02893' },
    { value: 'Antunes Auto Sales, Inc.', label: 'Antunes Auto Sales, Inc. - 322 Providence Street,West Warwick,RI,02893' },
    { value: 'Apollo Auto Sales, Inc.', label: 'Apollo Auto Sales, Inc. - 623-625 Broad Street,Cumberland,RI,02864' },
    { value: 'Aquidneck Motors, Inc.', label: 'Aquidneck Motors, Inc. - 360 West Main Road,Middletown,RI,02842' },
    { value: 'Arlington RV Supercenter, Inc.', label: 'Arlington RV Supercenter, Inc. - 966 Quaker Lane,East Greenwich ,RI,02818' },
    { value: 'Aspen Auto Sales, Inc', label: 'Aspen Auto Sales, Inc - 100 Railroad St,Manville,RI,02838' },
    { value: 'Astro Auto Sales, Inc.', label: 'Astro Auto Sales, Inc. - 60 Tiogue Avenue,West Warwick,RI,02893' },
    { value: 'Atlantic Autocenter, LLC', label: 'Atlantic Autocenter, LLC - 616 Atwood Avenue,Cranston,RI,02920' },
    { value: 'Atlantic Bays Auto Sales and Service', label: 'Atlantic Bays Auto Sales and Service - 61 Pilsudski Street,Providence ,RI,02909' },
    { value: 'Atlas Auto Sales', label: 'Atlas Auto Sales - 21 Arnold Farm Rd, West Greenwich, RI 02817' },
    { value: 'Audi Warwick', label: 'Audi Warwick - 1517D Bald Hill Road,Warwick,RI,02886' },
    { value: 'Audrain Automobile Museum, Inc', label: 'Audrain Automobile Museum, Inc - 222 Bellevue Avenue, Newport, RI 02840' },
    { value: 'Auto City, Inc.', label: 'Auto City, Inc. - 225 Plainfield Street,Providence,RI,02909' },
    { value: 'Auto Factory, Inc.', label: 'Auto Factory, Inc. - 460 Taunton Avenue,East Providence,RI,02914' },
    { value: 'Auto Gallery, Inc.', label: 'Auto Gallery, Inc. - 750-760 Main Road,Tiverton ,RI,02878' },
    { value: 'Auto Mart, Inc.', label: 'Auto Mart, Inc. - 1108 Park Avenue,Cranston,RI,02910' },
    { value: 'Auto Rossa Auto Sales LLC', label: 'Auto Rossa Auto Sales LLC - 2 New Industrial Way, Warren, RI 02885' },
    { value: 'Auto Service Center And Sales', label: 'Auto Service Center And Sales - 165 Frenchtown Rd,North Kingstown,RI,02852' },
    { value: 'Auto Village Sales & Service', label: 'Auto Village Sales & Service - 920 Tiogue Avenue,Coventry,RI,02816' },
    { value: 'Autoland, Inc.', label: 'Autoland, Inc. - 653 Tiogue Avenue,Coventry,RI,02816' },
    { value: 'Autoline Auto Sales, LLC', label: 'Autoline Auto Sales, LLC - 975 Charles Street ,North Providence,RI,02904' },
    { value: 'AutoMatchRI.com Auto Sales', label: 'AutoMatchRI.com Auto Sales - 342 Compass Circle Unit C-3,North Kingstown,RI,028522' },
    { value: 'Automed Auto Sales, Inc.', label: 'Automed Auto Sales, Inc. - 15 Aster Street,West Warwick,RI,02893' },
    { value: 'Autosport Sales & Collision, Inc.', label: 'Autosport Sales & Collision, Inc. - 640 Atwood Avenue,Cranston,RI,02920' },
    { value: 'Autowizard, Inc.', label: 'Autowizard, Inc. - 19E Lark Industrial Parkway,Greenville ,RI,02828' },
    { value: 'B&L Auto Sales', label: 'B&L Auto Sales - 824 Lonsdale Avenue,Central Falls,RI,02863' },
    { value: 'Bailey\'s Motor Sales, Inc.', label: 'Bailey\'s Motor Sales, Inc. - 425 Ten Rod Road,North Kingstown,RI,02852' },
    { value: 'Bald Hill Dodge-Chrysler-Jeep', label: 'Bald Hill Dodge-Chrysler-Jeep - 1035 Bald Hill Road,Warwick,RI,02886' },
    { value: 'Bald Hill Kia', label: 'Bald Hill Kia - 1021-1035 Bald Hill Road,Warwick,RI,02886' },
    { value: 'Balise Volkswagen', label: 'Balise Volkswagen - 525 Quaker Lane,West Warwick,RI,02893' },
    { value: 'Balise Chevrolet of Warwick', label: 'Balise Chevrolet of Warwick - 1338 Post Road,Warwick,RI,02888' },
    { value: 'Balise Honda of West Warwick', label: 'Balise Honda of West Warwick - 509 Quaker Lane,West Warwick,RI,02893' },
    { value: 'Balise Nissan', label: 'Balise Nissan - 1350 Post Road,Warwick,RI,02888' },
    { value: 'Balise Subaru', label: 'Balise Subaru - 561 Quaker Lane,West Warwick,RI,02893' },
    { value: 'Balise Toyota Of Warwick', label: 'Balise Toyota Of Warwick - 1400 Post Road,Warwick,RI,02888' },
    { value: 'Ballard Mack Sales & Service of RI, Inc.', label: 'Ballard Mack Sales & Service of RI, Inc. - 280 Scituate Avenue,Johnston,RI,02919' },
    { value: 'Barreiros Auto Sales, Inc.', label: 'Barreiros Auto Sales, Inc. - 620 Smithfield Avenue,Lincoln ,RI,02865' },
    { value: 'Beam Truck & Body, Inc.', label: 'Beam Truck & Body, Inc. - 433 Cumberland Hill Road, Route 122,Woonsocket,RI,02895' },
    { value: 'Bernier’s Auto & Trailer Sales, LLC', label: 'Bernier’s Auto & Trailer Sales, LLC - 620 Pond Street,Woonsocket ,RI,02895' },
    { value: 'Best Wheels Imports, LLC', label: 'Best Wheels Imports, LLC - 1162 Atwood Avenue,Johnston,RI,02919' },
    { value: 'Blackstone Auto Sales and Body, Inc.', label: 'Blackstone Auto Sales and Body, Inc. - 8-12 Ann & Hope Way,Cumberland,RI,02864' },
    { value: 'BMW of Newport', label: 'BMW of Newport - 1215 West Main Road, Middletown, RI 02842' },
    { value: 'BMW of Warwick', label: 'BMW of Warwick - 1515 Bald Hill Road,Warwick,RI,02886' },
    { value: 'Bob’s Motorcycle Sales', label: 'Bob’s Motorcycle Sales - 28 Main Street,Ashaway ,RI,02804' },
    { value: 'Brittany Motors, LTD', label: 'Brittany Motors, LTD - 159 Greenville Avenue,Johnston,RI,02919' },
    { value: 'Bucci’s Auto Sales, Inc.', label: 'Bucci’s Auto Sales, Inc. - 300 Mendon Road,Cumberland,RI,02864' },
    { value: 'Burrillville Motor Sales Inc.', label: 'Burrillville Motor Sales Inc. - 260 South Main Street,Pascoag ,RI,02859' },
    { value: 'C & S Specialty, Inc', label: 'C & S Specialty, Inc - 1172 Old Smithfield Road,North Smithfield,RI,02896' },
    { value: 'C & T Auto Sales', label: 'C & T Auto Sales - 577 Killingly Street,Johnston,RI,02919' },
    { value: 'Calco Auto Sales', label: 'Calco Auto Sales - 1309 Plainfield Street, Johnston, RI 02919' },
    { value: 'Cambio’s Auto Sales', label: 'Cambio’s Auto Sales - 615 Plainfield St,Providence ,RI,02909' },
    { value: 'Capital Auto Sales, Inc.', label: 'Capital Auto Sales, Inc. - 896 Manton Avenue,Providence,RI,02909' },
    { value: 'Capital Car Center, Inc.', label: 'Capital Car Center, Inc. - 734 Hartford Ave. Rear,Providence ,RI,02919' },
    { value: 'Capital City Auto Sales Main', label: 'Capital City Auto Sales Main - 25 Turner Street,Providence ,RI,02908' },
    { value: 'Capozzi’s Auto Sales & Salvage, Inc.', label: 'Capozzi’s Auto Sales & Salvage, Inc. - 2015 New London Tnpk RR-1,Coventry ,RI,02816' },
    { value: 'Caravan Auto', label: 'Caravan Auto - 1185 Cranston Street,Cranston,RI,02920' },
    { value: 'Carlos’ Auto Sales and Service', label: 'Carlos’ Auto Sales and Service - 1117 Central Ave,Pawtucket,RI,02861' },
    { value: 'CarMax', label: 'CarMax - 153 Bald Hill Road,Cranston,RI,02920' },
    { value: 'Carr’s Garage, Inc.', label: 'Carr’s Garage, Inc. - 396 Broad Street,Cumberland,RI,02864' },
    { value: 'Cars Unlimited', label: 'Cars Unlimited - 3755A Mendon Road,Cumberland ,RI,02864' },
    { value: 'Cartex Auto Sales, LLC', label: 'Cartex Auto Sales, LLC - 540 Weeden Street,Pawtucket ,RI,02860' },
    { value: 'Casale Auto Sales and Auto Body, Inc.', label: 'Casale Auto Sales and Auto Body, Inc. - 2741 Hartford Ave,Johnston,RI,02919' },
    { value: 'Casey’s Auto Sales', label: 'Casey’s Auto Sales - 2130 West Shore Rd,Warwick,RI,02886' },
    { value: 'Cerrito Brothers, Inc.', label: 'Cerrito Brothers, Inc. - 75 Mill Street,Johnston,RI,02919' },
    { value: 'Cerroni’s Auto Sales', label: 'Cerroni’s Auto Sales - 124 Pleasant View Ave ,Smithfield ,RI,02917' },
    { value: 'Certified Auto Sales & Service', label: 'Certified Auto Sales & Service - 43 Humbert Street,North Providence,RI,02911' },
    { value: 'Champion Collision & Sales, Inc.', label: 'Champion Collision & Sales, Inc. - 41 Congress Street,Pawtucket,RI,02860' },
    { value: 'Chestnut Hill Truck and Auto Sales, LLC', label: 'Chestnut Hill Truck and Auto Sales, LLC - 21 Calef Street,Cranston ,RI,02920' },
    { value: 'Chiqui Auto Sales & Muffler', label: 'Chiqui Auto Sales & Muffler - 601 Lonsdale Avenue,Central Falls,RI,02863' },
    { value: 'Christopher Motors, Inc.', label: 'Christopher Motors, Inc. - 1290 Greenwich Avenue,Warwick,RI,02886' },
    { value: 'Christy’s Auto Sales Inc.', label: 'Christy’s Auto Sales Inc. - 2 Sunnyside Avenue,Johnston,RI,02919' },
    { value: 'City Limit Auto Sales', label: 'City Limit Auto Sales - 760-A Hartford Avenue,Johnston,RI,02919' },
    { value: 'Class Act Motors, Inc.', label: 'Class Act Motors, Inc. - 475 Elmwood Avenue,Providence ,RI,02907' },
    { value: 'Coastal Auto Sales', label: 'Coastal Auto Sales - 540 Pawtucket Avenue,Pawtucket,RI,02860' },
    { value: 'Coastal International', label: 'Coastal International - 17 O’Keefe Lane,Warwick ,RI,02888' },
    { value: 'Coletta\'s Auto Sales', label: 'Coletta\'s Auto Sales - 250 Niantic Avenue,Providence,RI,02907' },
    { value: 'Commercial Motors, LLC', label: 'Commercial Motors, LLC - 1180 Douglas Ave, Rear,North Providence ,RI,02904' },
    { value: 'Copart AUCTION ONLY', label: 'Copart AUCTION ONLY - 10 Industrial Drive,Exeter ,RI,02822' },
    { value: 'Cousin’s Auto Sales', label: 'Cousin’s Auto Sales - 45 Foundry Street,Woonsocket,RI,02895' },
    { value: 'Cranston Auto Sales', label: 'Cranston Auto Sales - 19 Elena Street,Cranston,RI,02920' },
    { value: 'CSM Truck Sales', label: 'CSM Truck Sales - 87 Centre of New England Blvd, Coventry, RI 02816' },
    { value: 'Cumberland Hill Auto Sales & Service, Inc.', label: 'Cumberland Hill Auto Sales & Service, Inc. - 4084 Mendon Road,Cumberland ,RI,02864' },
    { value: 'Curtis Auto Sales', label: 'Curtis Auto Sales - 118 Curtis Street,Providence ,RI,02909' },
    { value: 'Custom Motors', label: 'Custom Motors - 2244 Pawtucket Avenue,East Providence ,RI,02914' },
    { value: 'Cycle Performance And Sales, LLC', label: 'Cycle Performance And Sales, LLC - 208 Bernon St.,Woonsocket,RI,02895' },
    { value: 'D & J Auto Sales, LLC', label: 'D & J Auto Sales, LLC - 836 Main Street,West Warwick,RI,02893' },
    { value: 'D&M Motor Sales, Inc.', label: 'D&M Motor Sales, Inc. - 50 Libera Street,Cranston ,RI,02920' },
    { value: 'D’Agostino Motors LTD', label: 'D’Agostino Motors LTD - 411 Douglas Pike,Smithfield,RI,02917' },
    { value: 'D’Agostino\'s Auto Sales and Salvage, Inc.', label: 'D’Agostino\'s Auto Sales and Salvage, Inc. - 1174 Douglas Avenue,North Providence,RI,02904' },
    { value: 'D’Ambra Auto Sales, Inc.', label: 'D’Ambra Auto Sales, Inc. - 169 Elmwood Avenue,Providence,RI,02907' },
    { value: 'Darlington Auto Sales and Auto Body', label: 'Darlington Auto Sales and Auto Body - 156 Benefit Street,Pawtucket,RI,02860' },
    { value: 'Detroit Motor Cars', label: 'Detroit Motor Cars - 1189 Douglas Avenue,North Providence ,RI,02904' },
    { value: 'Devaney Auto Sales And Service', label: 'Devaney Auto Sales And Service - 741 North Broadway,East Providence,RI,02914' },
    { value: 'Dick Shappy Vintage Auto Sales, LLC', label: 'Dick Shappy Vintage Auto Sales, LLC - 365 Charles St,Providence,RI,02904' },
    { value: 'Dijie Auto Sales & Service Corp.', label: 'Dijie Auto Sales & Service Corp. - 580 Killingly Street,Johnston,RI,02908' },
    { value: 'Dinola Auto Sales, Inc.', label: 'Dinola Auto Sales, Inc. - 1021 East Avenue,Oakland ,RI,02858' },
    { value: 'Distinctive Motor Cars Unlimited', label: 'Distinctive Motor Cars Unlimited - 1010 Plainfield Street,Johnston,RI,02919' },
    { value: 'Division Street Auto Sales & Service, Inc.', label: 'Division Street Auto Sales & Service, Inc. - 595 Division Street,Pawtucket,RI,02861' },
    { value: 'Donald’s Car Corner', label: 'Donald’s Car Corner - 295 Huntington Avenue,Providence,RI,02909' },
    { value: 'Dorman’s Auto Center, Inc. "Annex"', label: 'Dorman’s Auto Center, Inc. "Annex" - 124 Beverage Hill Avenue,Pawtucket,RI,02860' },
    { value: 'Dorman’s Auto Center, Inc. "Main"', label: 'Dorman’s Auto Center, Inc. "Main" - 434 Prospect Street,Pawtucket,RI,02860' },
    { value: 'Dunn\'s Corners Auto Sales & Repair', label: 'Dunn\'s Corners Auto Sales & Repair - 260 Post Road,Westerly,RI,02891' },
    { value: 'Durand’s Kawasaki Motorsports Sales', label: 'Durand’s Kawasaki Motorsports Sales - 147 Main Road,Tiverton,RI,02878' },
    { value: 'Dyer Avenue Motors', label: 'Dyer Avenue Motors - 454 Dyer Avenue,Cranston ,RI,02920' },
    { value: 'Eagle Motors, Inc.', label: 'Eagle Motors, Inc. - 172 Chapel Street,Harrisville ,RI,02830' },
    { value: 'East Bay Auto Sales, Inc.', label: 'East Bay Auto Sales, Inc. - 269 Market Street,Warren,RI,02885' },
    { value: 'East Coast Motor Sports and Auto Sales, Inc.', label: 'East Coast Motor Sports and Auto Sales, Inc. - 60 Aster Street,West Warwick,RI,02893' },
    { value: 'East Side Auto Sales and Collision Center', label: 'East Side Auto Sales and Collision Center - 2050 Plainfield Pike,Cranston,RI,02921' },
    { value: 'Ed’s Auto Sales, Inc', label: 'Ed’s Auto Sales, Inc - 681 North Broadway,East Providence ,RI,02914' },
    { value: 'Electra Auto Sales & Service', label: 'Electra Auto Sales & Service - 42 Putnam Avenue,Johnston,RI,02919' },
    { value: 'Elmwood Auto Sales', label: 'Elmwood Auto Sales - 358 Elmwood Ave,Providence,RI,02907' },
    { value: 'Elmwood Chrysler Dodge Jeep Ram', label: 'Elmwood Chrysler Dodge Jeep Ram - 625 Taunton Avenue,East Providence,RI,02914' },
    { value: 'Enterprise Car Sales', label: 'Enterprise Car Sales - 10 Senator St, Warwick, RI 02888' },
    { value: 'Epautosales', label: 'Epautosales - 2289 Pawtucket Avenue,East Providence,RI,02914' },
    { value: 'Executive Auto Sales', label: 'Executive Auto Sales - 296 George Washington Highway,Smithfield,RI,02917' },
    { value: 'Exeter Auto Repair & Sales', label: 'Exeter Auto Repair & Sales - 565 Nooseneck Hill Road,Exeter ,RI,02892' },
    { value: 'Exotic & Special Interest Cars', label: 'Exotic & Special Interest Cars - 144 Greenwich Avenue,Warwick,RI,02886' },
    { value: 'Family Auto Sales, Inc.', label: 'Family Auto Sales, Inc. - 386 George Waterman Rd,Johnston,RI,02919' },
    { value: 'Fenwood Auto Sales and Service', label: 'Fenwood Auto Sales and Service - 381 Gazza Rd,Mapleville,RI,02839' },
    { value: 'Finest Auto Sales', label: 'Finest Auto Sales - 36-38 Pleasant Valley Pky,Providence ,RI,02908' },
    { value: 'First Class Auto Sales', label: 'First Class Auto Sales - 815 Taunton Avenue, East Providence, RI 02914' },
    { value: 'Five Star Auto Sales', label: 'Five Star Auto Sales - 1348 Douglas Pike,Smithfield,RI,02917 Route 7' },
    { value: 'Fleetway Sales & Service, Inc.', label: 'Fleetway Sales & Service, Inc. - 170-D Amaral Street,East Providence ,RI,02915' },
    { value: 'Flood Ford of Narragansett', label: 'Flood Ford of Narragansett - 21 Woodruff Avenue,Narragansett,RI,02882' },
    { value: 'Flood Ford of East Greenwich', label: 'Flood Ford of East Greenwich - 2545 South County Trail, (Route 2),East Greenwich,RI,02818' },
    { value: 'Flood Mazda', label: 'Flood Mazda - 220 Old Tower Hill Road,Wakefield,RI,02879' },
    { value: 'Francis Auto Sales', label: 'Francis Auto Sales - 625 Metacom Avenue,Bristol,RI,02809' },
    { value: 'Frenchtown Auto Sales', label: 'Frenchtown Auto Sales - 3662 Quaker Lane,North Kingstown,RI,02852' },
    { value: 'FRIZZO AUTO SALES', label: 'FRIZZO AUTO SALES - 117 WEBSTER STREET,PAWTUCKET ,RI,02861' },
    { value: 'FSA Auto Sales And Repair', label: 'FSA Auto Sales And Repair - 624 York Ave,Pawtucket,RI,02861' },
    { value: 'Full Stop Auto Sales', label: 'Full Stop Auto Sales - 450 Potters Avenue,Providence,RI,02907' },
    { value: 'G.C.C. Auto Sales', label: 'G.C.C. Auto Sales - 175 Danielson Pike,Foster,RI,02825' },
    { value: 'GALINDA\'S AUTOMOTIVE SALES INC Main', label: 'GALINDA\'S AUTOMOTIVE SALES INC Main - 94 Broad Street,Cumberland,RI,02864' },
    { value: 'GALINDA\'S AUTOMOTIVE SALES INC Annex', label: 'GALINDA\'S AUTOMOTIVE SALES INC Annex - 187 Dexter Street,Cumberland,RI,02864' },
    { value: 'Gansett Auto Sales & Parts', label: 'Gansett Auto Sales & Parts - 206 Pine Street,Pawtucket,RI,02860' },
    { value: 'Garcia Auto Sales Inc', label: 'Garcia Auto Sales Inc - 110 Aldrich Street,Providence,RI,02905' },
    { value: 'Gateway Auto Sales, LLC', label: 'Gateway Auto Sales, LLC - 54 Oregon St.,Providence,RI,02908' },
    { value: 'Gemini Auto Sales', label: 'Gemini Auto Sales - 240 Silver Spring St,Providence,RI,02904' },
    { value: 'General Auto Sales, Inc.', label: 'General Auto Sales, Inc. - 384 King Road,Tiverton,RI,02878' },
    { value: 'Genesis of West Warwick', label: 'Genesis of West Warwick - 405 Quaker Lane, West Warwick RI 02893' },
    { value: 'George’s Auto Sales and Repair, Inc.', label: 'George’s Auto Sales and Repair, Inc. - 795 Victory Highway,Mapleville ,RI,02839' },
    { value: 'German Motors, Inc.', label: 'German Motors, Inc. - 879 North Main Street,Providence,RI,02904' },
    { value: 'Gershkoff Auto Sales', label: 'Gershkoff Auto Sales - 1085 Cranston Street,Cranston,RI,02920' },
    { value: 'Gino’s Auto Sales & Body Works, Inc.', label: 'Gino’s Auto Sales & Body Works, Inc. - 4 Tag Drive,North Providence ,RI,02911' },
    { value: 'GLS Auto Sales', label: 'GLS Auto Sales - 790 Wallum Lake Road,Pascoag ,RI,02858' },
    { value: 'Gold Star Auto Sales, Inc.', label: 'Gold Star Auto Sales, Inc. - 53 Greenville Avenue,Johnston,RI,02919' },
    { value: 'Grasso’s Auto Sales, Inc.', label: 'Grasso’s Auto Sales, Inc. - 1051 Chalkstone Avenue,Providence,RI,02908' },
    { value: 'Great Road Auto Sales', label: 'Great Road Auto Sales - 764 Great Road,North Smithfield,RI,02896' },
    { value: 'Greystone Motors, Inc.', label: 'Greystone Motors, Inc. - 129 Waterman Avenue,North Providence,RI,02911' },
    { value: 'Grieco Honda', label: 'Grieco Honda - 1880 Hartford Avenue,Johnston,RI,02919' },
    { value: 'Grieco Hyundai', label: 'Grieco Hyundai - 1890 Hartford Avenue,Johnston,RI,02919' },
    { value: 'Grieco Toyota', label: 'Grieco Toyota - 415 Taunton Avenue,East Providence,RI,02914' },
    { value: 'Hall’s Garage, Inc.', label: 'Hall’s Garage, Inc. - 56 Plainfield Pike,North Scituate,RI,02857 PO Box 37' },
    { value: 'Hamilton Auto Sales, LLC', label: 'Hamilton Auto Sales, LLC - 901 Boston Neck Road,North Kingstown,RI,02852' },
    { value: 'Happy Camper Auto and RV Sales', label: 'Happy Camper Auto and RV Sales - 24 Begonia Street, West Warwick, RI 02893' },
    { value: 'Herb Chambers Cadillac, Inc.', label: 'Herb Chambers Cadillac, Inc. - 1511 Bald Hill Road,Warwick,RI,02886' },
    { value: 'Herb Chambers Alfa Romeo of Warwick', label: 'Herb Chambers Alfa Romeo of Warwick - 1441 Bald Hill Road, Warwick, RI 02886' },
    { value: 'Herb Chambers Maserati of Warwick', label: 'Herb Chambers Maserati of Warwick - 1441 Bald Hill Road, Warwick, RI 02886' },
    { value: 'Heritage Auto Sales', label: 'Heritage Auto Sales - 62 Post Road,Warwick,RI,02888' },
    { value: 'Hernandez Auto Sales, Inc', label: 'Hernandez Auto Sales, Inc - 610 Weeden Street,Pawtucket,RI,02860' },
    { value: 'Heritage Auto Sales', label: 'Heritage Auto Sales - 62 Post Road,Warwick,RI,02888' },
    { value: 'Higgins Auto, LLC', label: 'Higgins Auto, LLC - 93-B Burdickville Rd,Charlestown,RI,02813' },
    { value: 'HI-Tech Auto Sales and Rentals', label: 'HI-Tech Auto Sales and Rentals - 322 Reservoir Avenue,Providence,RI,02907' },
    { value: 'Holiday Auto, Inc.', label: 'Holiday Auto, Inc. - 1295 High Street,Central Falls,RI,02863' },
    { value: 'Home Towne Auto "Annex"', label: 'Home Towne Auto "Annex" - 781 Victory Highway - Rte 102,North Smithfield,RI,02896' },
    { value: 'Home Towne Auto "Main"', label: 'Home Towne Auto "Main" - 73 Mt Pleasant Road ,North Smithfield,RI,02896' },
    { value: 'Hub’s Auto Sales, Inc.', label: 'Hub’s Auto Sales, Inc. - 915-925 Broad Street,Central Falls,RI,02963' },
    { value: 'Hurd Auto Mall', label: 'Hurd Auto Mall - 1705 Hartford Avenue,Johnston ,RI,02919' },
    { value: 'Hyundai of Newport', label: 'Hyundai of Newport - 1215 West Main Road, Middletown, RI 02842' },
    { value: 'Iannotti Bros. Select Cars', label: 'Iannotti Bros. Select Cars - 636 Tiogue Avenue,Coventry,RI,02816' },
    { value: 'Independent Auto Sales', label: 'Independent Auto Sales - 379 Roosevelt Avenue,Pawtucket,RI,02860' },
    { value: 'Industrial Motors, Inc.', label: 'Industrial Motors, Inc. - 31 Link Street,Pawtucket,RI,02861' },
    { value: 'Infiniti of Warwick', label: 'Infiniti of Warwick - 1085 Centerville Road,Warwick,RI,02886' },
    { value: 'Inner-City Auto Sales, Inc.', label: 'Inner-City Auto Sales, Inc. - 540 Huntington Avenue,Providence,RI,02907' },
    { value: 'Insurance Auto Auctions', label: 'Insurance Auto Auctions - 160 Amaral Street,East Providence,RI,02915' },
    { value: 'International Horsepower Auto Sales', label: 'International Horsepower Auto Sales - 910 Quaker Lane, Warwick, RI 02886' },
    { value: 'International Motor Group "Annex"', label: 'International Motor Group "Annex" - 4657 Post Road,Warwick,RI,02818' },
    { value: 'International Motor Group "Main"', label: 'International Motor Group "Main" - 4614 Post Road,Warwick,RI,02818' },
    { value: 'J&C Auto Sales, Inc.', label: 'J&C Auto Sales, Inc. - 65 Elm Street,Johnston,RI,02919' },
    { value: 'J&D Auto Sales, Inc.', label: 'J&D Auto Sales, Inc. - 4 Bridal Avenue- Unit C,West Warwick ,RI,02893' },
    { value: 'J&T Auto Sales', label: 'J&T Auto Sales - 561 Providence Street,Warwick,RI,02886' },
    { value: 'J.D. Byrider Auto Sales “Main”', label: 'J.D. Byrider Auto Sales “Main” - 615 Reservoir Avenue,Cranston,RI,02910' },
    { value: 'J.D.J. Auto Sales, LLC', label: 'J.D.J. Auto Sales, LLC - 568 Huntington Avenue,Providence,RI,02907' },
    { value: 'J.F.C. Auto Sales', label: 'J.F.C. Auto Sales - 904 Manton Avenue,Providence,RI,02909' },
    { value: 'Jack & Son Auto Sales and Service, Inc.', label: 'Jack & Son Auto Sales and Service, Inc. - 1012 Main Street,Pawtucket,RI,02860' },
    { value: 'Jake Kaplan’s LTD', label: 'Jake Kaplan’s LTD - 1346 Bald Hill Road, Warwick,RI,02886' },
    { value: 'JE Auto Sales LLC', label: 'JE Auto Sales LLC - 163 Mineral Spring Avenue,Pawtucket,RI,02860' },
    { value: 'Jim’s Auto Sales & Auto Body Works, Inc.', label: 'Jim’s Auto Sales & Auto Body Works, Inc. - 1153 Central Avenue,Pawtucket,RI,02861' },
    { value: 'Jimmy’s Auto Sales', label: 'Jimmy’s Auto Sales - 946 Charles St.,North Providence,RI,02904' },
    { value: 'Joe Auto Sales and Service', label: 'Joe\'s Auto Sales & Service - 1022 Mendon Road,Cumberland,RI,02864' },
    { value: 'Johnston Auto Sales, LLC', label: 'Johnston Auto Sales, LLC - 33 Putnam Avenue,Johnston,RI,02919' },
    { value: 'Jorge’s Auto Sales “Annex”', label: 'Jorge’s Auto Sales “Annex” - 5 Eli Street,Cumberland,RI,02864' },
    { value: 'Jorge’s Auto Sales “Main”', label: 'Jorge’s Auto Sales “Main” - 169 Broad Street,Cumberland,RI,02864' },
    { value: 'King Philip Motors', label: 'King Philip Motors - 331 Metacom Avenue,Bristol ,RI,02809' },
    { value: 'King Richard\'s Auto Center, Inc.', label: 'King Richard\'s Auto Center, Inc. - 801-803 Taunton Avenue,East Providence,RI,02914' },
    { value: 'Kingston Auto Sales, Inc.', label: 'Kingston Auto Sales, Inc. - 1880 Kingstown Rd,South Kingstown,RI,02879' },
    { value: 'Knox’s Garage', label: 'Knox’s Garage - 110 Gleaner Chapel Rd,North Scituate ,RI,02857' },
    { value: 'Lafazia Motors', label: 'Lafazia Motors - 920 Plainfield Street,Johnston ,RI,02919' },
    { value: 'Laires & Son Auto Sales & Repairs', label: 'Laires & Son Auto Sales & Repairs - 158 Waterman Avenue,East Providence ,RI,02914' },
    { value: 'Lagos Auto Sales and Service LLC', label: 'Lagos Auto Sales and Service LLC - 700 Douglas Avenue, Providence, RI 02908' },
    { value: 'Lajara Auto Sales', label: 'Lajara Auto Sales - 1141 Cranston Street,Cranston,RI,02920' },
    { value: 'Lake Auto Sales, Inc.', label: 'Lake Auto Sales, Inc. - 26 Social Street,Providence,RI,02904' },
    { value: 'Land Rover Warwick', label: 'Land Rover Warwick - 1346 Bald Hill Road,Warwick,RI,02886' },
    { value: 'Langway Nissan of Newport', label: 'Langway Nissan of Newport - 295 East Main Road,Middletown,RI,02842' },
    { value: 'Michael J\'s Auto Sales & Service', label: 'Michael J\'s Auto Sales & Service - 293 Waterman Avenue,Smithfield,RI,02917' },
    { value: 'Michael\'s Auto Sales, LLC', label: 'Michael\'s Auto Sales, LLC - 3 Tag Drive,North Providence,RI,02911' },
    { value: 'Miller\'s Truck Sales & Repair, Inc.', label: 'Miller\'s Truck Sales & Repair, Inc. - 145 Higginson Avenue,Lincoln,RI,02865' },
    { value: 'Mini of Warwick', label: 'Mini of Warwick - 1515A Bald Hill Road,Warwick,RI,02886' },
    { value: 'Miracle Auto Sales, Inc.', label: 'Miracle Auto Sales, Inc. - 580 Reservoir Avenue,Cranston ,RI,02910' },
    { value: 'Moe’s Auto Sales & Service, Inc.', label: 'Moe’s Auto Sales & Service, Inc. - 19-21 Benefit Street,Pawtucket,RI,02861 PO Box 2694' },
    { value: 'Mongeon Auto Next Gen Auto Sales, LLC', label: 'Mongeon Auto Next Gen Auto Sales, LLC - 1056 Eddie Dowling Hwy - Rte. 146,No Smithfield,RI,02896' },
    { value: 'Monte Carlo Auto Sales, Inc.', label: 'Monte Carlo Auto Sales, Inc. - 225 George Waterman Road,Johnston,RI,02919' },
    { value: 'Moretti’s Auto Sales', label: 'Moretti’s Auto Sales - 510 Atwood Avenue,Cranston,RI,02920' },
    { value: 'Motors East,Inc.', label: 'Motors East,Inc. - 268 Mendon Road,Cumberland,RI,02864' },
    { value: 'MTR Racing, Inc.', label: 'MTR Racing, Inc. - 372 Social Street,Woonsocket,RI,02895' },
    { value: 'Municipal Auto Sales, Inc.', label: 'Municipal Auto Sales, Inc. - 2628 West Shore Rd,Warwick,RI,02889' },
    { value: 'Mutter Motors, Inc.', label: 'Mutter Motors, Inc. - 505 Broad Street,Cumberland ,RI,02864' },
    { value: 'New Century Auto Sales, Inc.', label: 'New Century Auto Sales, Inc. - 1249 Plainfield Street,Johnston,RI,02919' },
    { value: 'New England Auto Sales', label: 'New England Auto Sales - 28 Whitford Street,Warwick,RI,02886' },
    { value: 'New Rides Auto Sales & Service, LLC', label: 'New Rides Auto Sales & Service, LLC - 925 Charles Street,North Providence,RI,02904' },
    { value: 'Nick’s Auto Sales', label: 'Nick’s Auto Sales - 44 Bradford Street,Providence,RI,02903' },
    { value: 'North American Auto Sales "Annex"', label: 'North American Auto Sales "Annex" - 915 Charles Street,North Providence,RI,02904' },
    { value: 'North American Auto Sales "MAIN"', label: 'North American Auto Sales "MAIN" - 350 Silver Spring Street,Providence ,RI,02904' },
    { value: 'North Smithfield Auto Sales, Inc.', label: 'North Smithfield Auto Sales, Inc. - 770 Eddie Dowling Hwy,North Smithfield ,RI,02896' },
    { value: 'Northeast Trailer Remarketing Sales', label: 'Northeast Trailer Remarketing Sales - 20 Business Park Drive, Smithfield, RI 02896' },
    { value: 'Nucar Tarbox Hyundai', label: 'Nucar Tarbox Hyundai - 3665 Quaker Lane,North Kingstown,RI,02852' },
    { value: 'Nucar Tarbox Toyota', label: 'Nucar Tarbox Toyota - 3671 Quaker Lane,North Kingstown ,RI,02852' },
    { value: 'Nuni\'s Auto Sales & Service', label: 'Nuni\'s Auto Sales & Service - 252 Manton Avenue,Providence,RI,02909' },
    { value: 'Ocean Chrysler Dodge Jeep Ram', label: 'Ocean Chrysler Dodge Jeep Ram - 9 Post Road, Westerly,RI,02891' },
    { value: 'Ocean Newport CDJR, Inc', label: 'Ocean Newport CDJR, Inc - 310 West Main Rd,Middletown,RI,02842' },
    { value: 'Ocean State Auto Sales', label: 'Ocean State Auto Sales - 146 Putnam Pike, Johnston, RI 02919' },
    { value: 'Ocean State Harley Davidson Shop', label: 'Ocean State Harley Davidson Shop - 435 Nooseneck Hill Road,Exeter,RI,02822' },
    { value: 'Onsite Truck Repair & Auto Sales', label: 'Onsite Truck Repair & Auto Sales - 34 Colfax Street,Pawtucket,RI,02860' },
    { value: 'Outkast Truck Sales', label: 'Outkast Truck Sales - 222 Lincoln Avenue,Warwick,RI,02888' },
    { value: 'P&J Auto Sales, Inc.', label: 'P&J Auto Sales, Inc. - 550 Prairie Avenue,Providence ,RI,02905' },
    { value: 'Park Avenue Auto Sales', label: 'Park Avenue Auto Sales - 716 Park Ave,Cranston ,RI,02910' },
    { value: 'Partners Auto Auction RI', label: 'Partners Auto Auction RI - 1 Snagwood Road - Route 6,Foster,RI,02825' },
    { value: 'Passport Automotive Group', label: 'Passport Automotive Group - 85 Budlong Road,Cranston,RI,02920' },
    { value: 'Pat’s Auto Sales Auto Body, Inc.', label: 'Pat’s Auto Sales Auto Body, Inc. - 363 George Waterman Rd,Johnston,RI,02919' },
    { value: 'Patriot Autocenter, LLC', label: 'Patriot Autocenter, LLC - 197 Simmonsville Avenue,Johnston,RI,02919' },
    { value: 'Paul Masse Buick-GMC South, Inc.', label: 'Paul Masse Buick-GMC South, Inc. - 2909 Tower Hill Road,South Kingstown,RI,02874' },
    { value: 'Paul Masse Chevrolet South, Inc.', label: 'Paul Masse Chevrolet South, Inc. - 399 Main Street,Wakefield,RI,02879' },
    { value: 'Paul Masse Chevrolet, Inc.', label: 'Paul Masse Chevrolet, Inc. - 1111 Taunton Avenue,East Providence,RI,02914' },
    { value: 'Pavilion Auto Sales, Inc.', label: 'Pavilion Auto Sales, Inc. - 1211 Cranston Street,Cranston ,RI,02920' },
    { value: 'Perlow’s Auto Sales "Annex"', label: 'Perlow’s Auto Sales "Annex" - 589 Pawtucket Avenue,Pawtucket,RI,02860' },
    { value: 'Perlow’s Auto Sales “Main”', label: 'Perlow’s Auto Sales “Main” - 56 Nashua Street,Pawtucket,RI,02860' },
    { value: 'Pistacchio Auto Service Center & Sales', label: 'Pistacchio Auto Service Center & Sales - 11 Old Pocasset Road,Johnston,RI,02919' },
    { value: 'Plainfield Auto Sales, Inc.', label: 'Plainfield Auto Sales, Inc. - 292 Plainfield St,Providence,RI,02909' },
    { value: 'Plante’s Auto Sales', label: 'Plante’s Auto Sales - 39 Parker Street,Woonsocket ,RI,02895' },
    { value: 'PM Auto Sales', label: 'PM Auto Sales - 31 Humbert Street, North Providence, RI 02911' },
    { value: 'PMG Auto Sales', label: 'PMG Auto Sales - 1361 Mineral Spring Avenue,North Providence,RI,02904' },
    { value: 'Porcelli\'s Auto Sales', label: 'Porcelli\'s Auto Sales - 301 Providence Street,West Warwick,RI,02893' },
    { value: 'Porsche Warwick', label: 'Porsche Warwick - 1517A Bald Hill Road,Warwick,RI,02886' },
    { value: 'Portsmouth Auto Sales & Repair', label: 'Portsmouth Auto Sales & Repair - 1955 East Main Rd,Portsmouth,RI,02871' },
    { value: 'Post Road Motors Sales & Body', label: 'Post Road Motors Sales & Body - 7335 Post Road,North Kingstown ,RI,02852' },
    { value: 'Powell Motors', label: 'Powell Motors - 700 St Paul Street,North Smithfield,RI,02895' },
    { value: 'Precision Auto Sales & Body Works, Inc.', label: 'Precision Auto Sales & Body Works, Inc. - 100 South Street,Johnston,RI,02919' },
    { value: 'Precision Harley Davidson, Inc.', label: 'Precision Harley Davidson, Inc. - 269 Armistice Boulevard,Pawtucket ,RI,02860' },
    { value: 'Premier Automotive Sales "Annex"', label: 'Premier Automotive Sales "Annex" - 1184 Warwick Avenue, Warwick, RI 02888' },
    { value: 'Premier Automotive Sales "Main"', label: 'Premier Automotive Sales "Main" - 375 Miantonomo Drive, Warwick, RI 02888' },
    { value: 'Premium Auto Sales, LLC', label: 'Premium Auto Sales, LLC - 32 Stafford Road,Tiverton,RI,02878' },
    { value: 'Prestige Mitsubishi', label: 'Prestige Mitsubishi - 377 Taunton Avenue,East Providence,RI,02914' },
    { value: 'Prestige Motorcars', label: 'Prestige Motorcars - 1124 Bald Hill Road,Warwick,RI,02886' },
    { value: 'Prime Cars USA Auto Sales LLC', label: 'Prime Cars USA Auto Sales LLC - 616 West Shore Road, Warwick, RI 02889' },
    { value: 'Quality Auto Sales and Service LLC', label: 'Quality Auto Sales and Service LLC - 100 Aldrich St, Providence, RI 02905' },
    { value: 'R & A Auto Sales', label: 'R & A Auto Sales - 1171-1173 Park Avenue,Cranston,RI,02910' },
    { value: 'R. Teto Motor Sales, Inc.', label: 'R. Teto Motor Sales, Inc. - 31 Congress Street,Pawtucket,RI,02861' },
    { value: 'Ralph & Sons Auto Sales', label: 'Ralph & Sons Auto Sales - 456 W Fountain Street,Providence ,RI,02903' },
    { value: 'Ranaldi Motors', label: 'Ranaldi Motors - 598 Atwood Avenue,Cranston ,RI,02920' },
    { value: 'Rapoza’s Quality Automobiles', label: 'Rapoza’s Quality Automobiles - 344 Fish Road,Tiverton ,RI,02878' },
    { value: 'Razee Motorcycle Center, Inc.', label: 'Razee Motorcycle Center, Inc. - 730 Tower Hill Road,North Kingstown,RI,02852' },
    { value: 'Reliable Auto Sales', label: 'Reliable Auto Sales - 31 Providence Street, West Warwick, RI 02893' },
    { value: 'Retro Auto Sales', label: 'Retro Auto Sales - 2096 West Shore Road, Warwick, RI 02889' },
    { value: 'Rhode Island Truck & Equipment Corp.', label: 'Rhode Island Truck & Equipment Corp. - 1331 Main Street,West Warwick,RI,02893' },
    { value: 'Rhode Island Truck Center, LLC', label: 'Rhode Island Truck Center, LLC - 155 Amaral Street, Riverside, RI 02915' },
    { value: 'Richmond Motor Sales, Inc "ANNEX"', label: 'Richmond Motor Sales, Inc "ANNEX" - 550 Pawtucket Avenue,Pawtucket,RI,02860' },
    { value: 'Richmond Motor Sales, Inc "ANNEX"', label: 'Richmond Motor Sales, Inc "ANNEX" - 519 Pawtucket Avenue,Pawtucket,RI,02860' },
    { value: 'Richmond Motor Sales, Inc. "MAIN"', label: 'Richmond Motor Sales, Inc. "MAIN" - 700 North Main Street,Providence,RI,02904' },
    { value: 'Rick\'s Tire and Auto Center and Auto Sales', label: 'Rick\'s Tire and Auto Center and Auto Sales - 1435 Victory Highway, Slatersville, RI 02879' },
    { value: 'Rivas Auto Sales & Repairs, Inc.', label: 'Rivas Auto Sales & Repairs, Inc. - 11 Roger Williams Ave,Providence,RI,02907' },
    { value: 'Riverside Auto Sales and Service', label: 'Riverside Auto Sales and Service - 450 Bullocks Point Avenue, Riverside, RI 02915' },
    { value: 'Roger Williams Auto Sales', label: 'Roger Williams Auto Sales - 60 Providence Street,West Warwick,RI,02893' },
    { value: 'Rossi Auto Care Sales & Service, Inc.', label: 'Rossi Auto Care Sales & Service, Inc. - 22 Tiogue Avenue,West Warwick,RI,02893' },
    { value: 'Rounds Auto Sales Co., Inc.', label: 'Rounds Auto Sales Co., Inc. - 61 Hartford Avenue,North Scituate,RI,02857' },
    { value: 'Route 146 Auto Sales, Inc.', label: 'Route 146 Auto Sales, Inc. - 1097 Eddie Dowling Hwy,N Smithfield,RI,02896' },
    { value: 'Route 44 Auto Sales, Inc.', label: 'Route 44 Auto Sales, Inc. - 675 Putnam Pike,Greenville ,RI,02828' },
    { value: 'Route 2 Mitsubishi', label: 'Route 2 Mitsubishi - 870 Quaker Lane,Warwick,RI,02886' },
    { value: 'Route 5 Auto Sales & Service', label: 'Route 5 Auto Sales & Service - 42 Sanderson Rd,Smithfield,RI,02917' },
    { value: 'RS Auto Sales & Rental', label: 'RS Auto Sales & Rental - 765 Main Street,Pawtucket ,RI,02860' },
    { value: 'Rt 6 Auto Sales', label: 'Rt 6 Auto Sales - 2160 Hartford Avenue,Johnston,RI,02919' },
    { value: 'Russ’ Ocean State Harley Davidson', label: 'Russ’ Ocean State Harley Davidson - 35 Albany Road,Warwick,RI,02888' },
    { value: 'Russo’s Auto Sales, Inc.', label: 'Russo’s Auto Sales, Inc. - 519 Dyer Avenue,Cranston ,RI,02920' },
    { value: 'Ryder Vehicle Sales, LLC', label: 'Ryder Vehicle Sales, LLC - 7 Jefferson Blvd,Warwick ,RI,02888' },
    { value: 'S & D Road Service & Auto Sales', label: 'S & D Road Service & Auto Sales - 9 Whipple Street, Cumberland, RI 02864' },
    { value: 'S & S Auto Sales & Repair', label: 'S & S Auto Sales & Repair - 432 Valley Street,Providence,RI,02908' },
    { value: 'S&H Auto Sales', label: 'S&H Auto Sales - 405 Washington St,Coventry,RI,02816' },
    { value: 'Saccucci Honda', label: 'Saccucci Honda - 1350 West Main Road, Middletown, RI, 02842' },
    { value: 'Safeway Auto Sales, Inc. "Main"', label: 'Safeway Auto Sales, Inc. "Main" - 61 Gooding Avenue, Bristol, RI, 02809' },
    { value: 'Sam\'s Auto Sales "Main"', label: 'Sam\'s Auto Sales "Main" - 936 Cranston Street, Cranston, RI, 02920' },
    { value: 'Sandy Lane Auto Sales and Repair', label: 'Sandy Lane Auto Sales and Repair - 2672 West Shore Road, Warwick, RI, 02889' },
    { value: 'Sandy Motors, Inc.', label: 'Sandy Motors, Inc. - 118 Sandy Bottom Road, Coventry, RI, 02816' },
    { value: 'Scott Volkswagen', label: 'Scott Volkswagen - 777 Taunton Avenue, East Providence, RI, 02914' },
    { value: 'Shannon Motors', label: 'Shannon Motors - 648 Killingly Street, Johnston, RI, 02919' },
    { value: 'Shannon Motors Woonsocket', label: 'Shannon Motors Woonsocket - 50 Founders Drive, Woonsocket, RI, 02895' },
    { value: 'Shoreline Auto Sales, LLC', label: 'Shoreline Auto Sales, LLC - 93A Kingstown Road, Richmond, RI, 02898' },
    { value: 'Simon Auto Group', label: 'Simon Auto Group - 1038-1040 Charles Street, North Providence, RI, 02904' },
    { value: 'Smith Street Auto Sales and Repair', label: 'Smith Street Auto Sales and Repair - 1524 Smith Street, North Providence, RI, 02911' },
    { value: 'Smithfield Classic Cars & Auto Sales LLC', label: 'Smithfield Classic Cars & Auto Sales LLC - 278 Douglas Pike, Smithfield, RI, 02917' },
    { value: 'Smithfield Motor Sales, Inc.', label: 'Smithfield Motor Sales, Inc. - 527 Smithfield Avenue, Pawtucket, RI, 02860' },
    { value: 'Soda Motors Auto Sales, LLC', label: 'Soda Motors Auto Sales, LLC - 312 Connell Highway, Newport, RI, 02840' },
    { value: 'Solution Auto Sales & Body "Annex"', label: 'Solution Auto Sales & Body "Annex" - 40-48 Reservoir Avenue, Providence, RI, 02907' },
    { value: 'Solution Auto Sales & Body "Main"', label: 'Solution Auto Sales & Body "Main" - 17 Warren Street, Providence, RI, 02907' },
    { value: 'Sousa’s Auto Sales & Body', label: 'Sousa’s Auto Sales & Body - 1442 Newport Ave, Pawtucket, RI, 02861' },
    { value: 'Speedcraft Acura', label: 'Speedcraft Acura - 883 Quaker Lane, West Warwick, RI, 02893' },
    { value: 'Speedcraft Nissan', label: 'Speedcraft Nissan - 885 Quaker Lane, West Warwick, RI, 02893' },
    { value: 'Speedcraft Volkswagen', label: 'Speedcraft Volkswagen - 104 Old Tower Hill Rd, Wakefield, RI, 02879' },
    { value: 'Stafford Auto Sales', label: 'Stafford Auto Sales - 1296 Stafford Road, Tiverton, RI, 02878' },
    { value: 'Stamas Auto & Truck Center, Inc.', label: 'Stamas Auto & Truck Center, Inc. - 1045 Cranston Street, Cranston, RI, 02920' },
    { value: 'State Auto Sales', label: 'State Auto Sales - 380 Valley Street, Providence, RI, 02908' },
    { value: 'Stateline Nissan', label: 'Stateline Nissan - 845 Taunton Avenue, East Providence, RI, 02914' },
    { value: 'Stateside Auto Sales', label: 'Stateside Auto Sales - 200 Washington Street, West Warwick, RI, 02893' },
    { value: 'Steingold Volvo', label: 'Steingold Volvo - 766 Broadway, Pawtucket, RI, 02861' },
    { value: 'Stephens Auto Sales', label: 'Stephens Auto Sales - 35 Quaker Lane, West Warwick, RI, 02893' },
    { value: 'Stevie D\'s Auto Sales and Service', label: 'Stevie D\'s Auto Sales and Service - 2570 Warwick Avenue, Warwick, RI, 02889' },
    { value: 'Stone Motors', label: 'Stone Motors - 760 Great Road, North Smithfield, RI, 02896' },
    { value: 'Supreme Auto, Inc.', label: 'Supreme Auto, Inc. - 22 Walker Street, Lincoln, RI, 02865' },
    { value: 'Tasca Buick GMC', label: 'Tasca Buick GMC - 55 Fortin Drive, Woonsocket, RI, 02895' },
    { value: 'Tasca Chevrolet', label: 'Tasca Chevrolet - 114 Fortin Drive, Woonsocket, RI, 02895' },
    { value: 'Tasca Chrysler Dodge Jeep Ram Fiat', label: 'Tasca Chrysler Dodge Jeep Ram Fiat - 1667 Hartford Avenue, Johnston, RI, 02919' },
    { value: 'Tasca Ford', label: 'Tasca Ford - 1250-1300 Pontiac Ave, Cranston, RI, 02910' },
    { value: 'Tasca Kia', label: 'Tasca Kia - 1660-1670 Hartford Avenue, Johnston, RI, 02919' },
    { value: 'Tasca Lincoln Mercury', label: 'Tasca Lincoln Mercury - 1250-1300 Pontiac Avenue, Cranston, RI, 02910' },
    { value: 'Tasca Mazda', label: 'Tasca Mazda - 1250-1300 Pontiac Avenue, Cranston, RI, 02910' },
    { value: 'Tasca Volvo', label: 'Tasca Volvo - 1250-1300 Pontiac Avenue, Cranston, RI, 02910' },
    { value: 'Ted’s Auto Sales', label: 'Ted’s Auto Sales - 326 Broad Street, Central Falls, RI, 02863' },
    { value: 'Terry’s Auto, Limited', label: 'Terry’s Auto, Limited - 36 Blackstone Street, Woonsocket, RI, 02895' },
    { value: 'Tesla', label: 'Tesla - 399 Bald Hill Road, Warwick, RI, 02886' },
    { value: 'The Car Lot, Inc. "Annex"', label: 'The Car Lot, Inc. "Annex" - 1400 Plainfield Pike, Cranston, RI, 02920' },
    { value: 'The Car Lot, Inc. "Main"', label: 'The Car Lot, Inc. "Main" - 441 Dyer Avenue, Cranston, RI, 02920' },
    { value: 'The Peterbilt Store - Rhode Island', label: 'The Peterbilt Store - Rhode Island - 11 Industrial Lane, Johnston, RI, 02919' },
    { value: 'The Scooter Palace', label: 'The Scooter Palace - 50 Stafford Road, Tiverton, RI, 02878' },
    { value: 'Tiki\'s Auto Sales "Annex"', label: 'Tiki\'s Auto Sales "Annex" - 772 Main Street, Pawtucket, RI, 02860' },   
    { value: 'Tiki\'s Auto Sales "Main"', label: 'Tiki\'s Auto Sales "Main" - 66 Hilton Street, Pawtucket, RI, 02860' },
    { value: 'Tiverton Motor Sales, Inc.', label: 'Tiverton Motor Sales, Inc. - 541 Bulgarmarsh Road, Tiverton, RI, 02878' },
    { value: 'Tomassini’s Drivers Choice Car Co "Annex"', label: 'Tomassini’s Drivers Choice Car Co "Annex" - 494 Cumberland Hill Road, Woonsocket, RI, 02895' },
    { value: 'Tomassini’s Drivers Choice Car Co. "Main"', label: 'Tomassini’s Drivers Choice Car Co. "Main" - 7 Columbus Avenue, Woonsocket, RI, 02895' },
    { value: 'Tomasso’s Auto Sales', label: 'Tomasso’s Auto Sales - 729 East Avenue, Pawtucket, RI, 02860' },
    { value: 'Tony Luis Auto Sales & Service, Inc.', label: 'Tony Luis Auto Sales & Service, Inc. - 110 Dexter Street, Cumberland, RI, 02864' },
    { value: 'Tony’s Auto Sales & Service', label: 'Tony’s Auto Sales & Service - 10 Pier Road, East Providence, RI, 02914' },
    { value: 'Topline Motors, Inc.', label: 'Topline Motors, Inc. - 785 Cumberland Hill Road, Woonsocket, RI, 02895' },
    { value: 'Tourbillon Truck & Trailer Sales', label: 'Tourbillon Truck & Trailer Sales - 401 Snake Hill Road, North Scituate, RI, 02857' },
    { value: 'Town and Country Auto Sales, Inc.', label: 'Town and Country Auto Sales, Inc. - 26A Main Street, Ashaway, RI, 02804' },
    { value: 'Towne Auto Sales', label: 'Towne Auto Sales - 627 Killingly Street, Johnston, RI, 02919' },
    { value: 'Towne Motor Sales, Inc.', label: 'Towne Motor Sales, Inc. - 109 Main Road, Tiverton, RI, 02878' },
    { value: 'Toyota of Smithfield', label: 'Toyota of Smithfield - 550 George Washington Hwy, Smithfield, RI, 02917' },
    { value: 'Trail Auto Sales, Inc.', label: 'Trail Auto Sales, Inc. - 245 Wampanoag Trail, East Providence, RI, 02915' },
    { value: 'Truck Solutions Solutions Sales and Service, LLC', label: 'Truck Solutions Solutions Sales and Service, LLC - 125 Industrial Highway, Slatersville, RI, 02896 P.O. BOX 979' },
    { value: 'Twiggs Auto Sales', label: 'Twiggs Auto Sales - 205 Child Street, Warren, RI, 02885' },
    { value: 'Ultra Auto Sales, LLC', label: 'Ultra Auto Sales, LLC - 7 Ashton Parkway, Cumberland, RI, 02864' },
    { value: 'United Auto Sales, Inc.', label: 'United Auto Sales, Inc. - 734 Hartford Avenue, Providence, RI, 02919' },
    { value: 'Valenti Subaru, Inc.', label: 'Valenti Subaru, Inc. - 4 Langworthy Road, Westerly, RI, 02891' },
    { value: 'Valenti Toyota', label: 'Valenti Toyota - 6 Langworthy Road, Westerly, RI, 02891' },
    { value: 'Valley Street Auto Sales', label: 'Valley Street Auto Sales - 466 Valley Street, Providence, RI, 02908' },
    { value: 'Variety Auto Sales', label: 'Variety Auto Sales - 221 Washington Highway Route 116, Smithfield, RI, 02917' },
    { value: 'Viti, Inc.', label: 'Viti, Inc. - 975 Fish Road, Tiverton, RI, 02878' },
    { value: 'Volare Motors', label: 'Volare Motors - 1003 Park Avenue, Cranston, RI, 02910' },
    { value: 'Volvo of Tiverton', label: 'Volvo of Tiverton - 975 Fish Road, Tiverton, RI, 02878' },
    { value: 'Walsh’s Auto Body & Sales, Inc.', label: 'Walsh’s Auto Body & Sales, Inc. - 60 Narragansett Ave, Providence, RI, 02907' },
    { value: 'Warwick Auto Sales, Inc.', label: 'Warwick Auto Sales, Inc. - 1828 Elmwood Avenue, Warwick, RI, 02888' },
    { value: 'Wellington Auto Sales', label: 'Wellington Auto Sales - 77B Armento Street, Johnston, RI, 02919' },
    { value: 'West End Auto Sales & Collision Service Inc', label: 'West End Auto Sales & Collision Service Inc - 555 Cranston Street, Providence, RI, 02907' },
    { value: 'West Fountain Auto Sales & Body, Inc.', label: 'West Fountain Auto Sales & Body, Inc. - 400 West Fountain Street, Providence, RI, 02903' },
    { value: 'West Park Auto Sales', label: 'West Park Auto Sales - 195-B West Park St, Providence, RI, 02908' },
    { value: 'West Warwick Auto City, Inc.', label: 'West Warwick Auto City, Inc. - 93 Tiogue Avenue, West Warwick, RI, 02893' },
    { value: 'Westerly Auto Sales, Inc.', label: 'Westerly Auto Sales, Inc. - 74 School Street, Westerly, RI, 02891' },
    { value: 'Westminster Motors, LTD "Main"', label: 'Westminster Motors, LTD "Main" - 550 Valley Street, Providence, RI, 02908' },
    { value: 'Wheel’s of Freedom Cycle', label: 'Wheel’s of Freedom Cycle - 121 Benefit Street, Pawtucket, RI, 02861' },
    { value: 'Windmill Auto Sales & Body, Inc.', label: 'Windmill Auto Sales & Body, Inc. - 16 Humbert Street, North Providence, RI, 02911' },
    { value: 'Woonsocket Motors', label: 'Woonsocket Motors - 5 Madison Avenue, Woonsocket, RI, 02895' },
    { value: 'Ziggy’s Auto Sales, Inc.', label: 'Ziggy’s Auto Sales, Inc. - 3961 Quaker Lane, North Kingstown, RI, 02852' },
    { value: 'Zink\'s Auto Sales & Service', label: 'Zink\'s Auto Sales & Service - 550 Atwood Avenue, Cranston, RI, 02920' },
    { value: 'Zippy Auto Sales, Inc', label: 'Zippy Auto Sales, Inc - 450 Social Street, Woonsocket, RI, 02895' },
  ];

export const auto_out_of_state_address = [
    {value: 'Volkswagen of North Attleboro', label: 'Volkswagen of North Attleboro - 563 Kelley Blvd #152, North Attleborough, MA 02760'},
    {value: 'Boch Nissan South', label: 'Boch Nissan South - 685 S Washington St, North Attleborough, MA 02760'},
    {value: 'Patriot Subaru of North Attleboro ', label: 'Patriot Subaru of North Attleboro - 551 S Washington St, North Attleborough, MA 02760'},
    {value: 'Boch Toyota South', label: 'Boch Toyota South - 620 S Washington St, North Attleborough, MA 02760'},
    {value: 'Patriot Subaru of North Attleboro', label: 'Patriot Subaru of North Attleboro - 551 S Washington St, North Attleborough, MA 02760'},
    {value: 'Kia of Attleboro', label: 'Kia of Attleboro - 795 Newport Ave South Attleboro, MA 02703'},
    {value: 'Stateline Subaru', label: 'Stateline Subaru - 1451 Brayton Point Rd, Somerset, MA 02725'},
    {value: 'Courtesy Mitsubishi', label: 'Courtesy Mitsubishi - 11 Scott St, Attleboro, MA 02703'},
    {value: 'Milford Nissan', label: 'Milford Nissan – 320 East Main St, Milford MA 01757'},
    {value: 'Bob Valenti Chevrolet', label: 'Bob Valenti Chevrolet - 72 Jerry Browne Rd, Mystic, CT 06355'},
    {value: 'Copeland Chevrolet', label: 'Copeland Chevrolet - 955 Pearl St, Brockton, MA 02301'},
    {value: 'McGovern Hyundai', label: 'McGovern Hyundai – 240 Manley St, Brockton, MA 02301'},
    {value: 'McGovern Chevrolet', label: 'McGovern Chevrolet – 54 Main St, Greenfield, MA 01301'},
    {value: 'Imperial Ford', label: 'Imperial Ford – 8 Uxbridge Rd, Mendon, MA 01756'},
    {value: 'Putnam Kia', label: 'Putnam Kia – 157 Providence Pike, Rt, 44, Putnam, CT 06260'},
    {value: 'Marlboro Nissan', label: 'Marlboro Nissan – 740 Boston Post Rd E, Marlborough, MA 01752'},
    {value: '1A Auto Sales', label: '1A Auto Sales – 1449 Main St, Walpole, MA 02081'}, 
    {value: 'Bristol Toyota', label: 'Bristol Toyota - 2283 Grand Army of the Republic Hwy, Swansea, MA 02777'}, 
  ];
  