export const RhodeIslandCities = [
    { value: 'Ashaway, RI', label: 'Ashaway, RI' },
    { value: 'Barrington, RI', label: 'Barrington, RI' },
    { value: 'Bradford, RI', label: 'Bradford, RI' },
    { value: 'Bristol, RI', label: 'Bristol, RI' },
    { value: 'Central Falls, RI', label: 'Central Falls, RI' },
    { value: 'Charlestown, RI', label: 'Charlestown, RI' },
    { value: 'Coventry, RI', label: 'Coventry, RI' },
    { value: 'Cranston, RI', label: 'Cranston, RI' },
    { value: 'Cumberland, RI', label: 'Cumberland, RI' },
    { value: 'East Greenwich, RI', label: 'East Greenwich, RI' },
    { value: 'East Providence, RI', label: 'East Providence, RI' },
    { value: 'Exeter, RI', label: 'Exeter, RI' },
    { value: 'Foster, RI', label: 'Foster, RI' },
    { value: 'Greenville, RI', label: 'Greenville, RI' },
    { value: 'Harrisville, RI', label: 'Harrisville, RI' },
    { value: 'Hope Valley, RI', label: 'Hope Valley, RI' },
    { value: 'Hopkinton, RI', label: 'Hopkinton, RI' },
    { value: 'Jamestown, RI', label: 'Jamestown, RI' },
    { value: 'Johnston, RI', label: 'Johnston, RI' },
    { value: 'Kingston, RI', label: 'Kingston, RI' },
    { value: 'Lincoln, RI', label: 'Lincoln, RI' },
    { value: 'Little Compton, RI', label: 'Little Compton, RI' },
    { value: 'Middletown, RI', label: 'Middletown, RI' },
    { value: 'Narragansett, RI', label: 'Narragansett, RI' },
    { value: 'Newport, RI', label: 'Newport, RI' },
    { value: 'North Kingstown, RI', label: 'North Kingstown, RI' },
    { value: 'North Providence, RI', label: 'North Providence, RI' },
    { value: 'North Smithfield, RI', label: 'North Smithfield, RI' },
    { value: 'Pascoag, RI', label: 'Pascoag, RI' },
    { value: 'Pawtucket, RI', label: 'Pawtucket, RI' },
    { value: 'Portsmouth, RI', label: 'Portsmouth, RI' },
    { value: 'Providence, RI', label: 'Providence, RI' },
    { value: 'Smithfield, RI', label: 'Smithfield, RI' },
    { value: 'Tiverton, RI', label: 'Tiverton, RI' },
    { value: 'Wakefield, RI', label: 'Wakefield, RI' },
    { value: 'Warren, RI', label: 'Warren, RI' },
    { value: 'Warwick, RI', label: 'Warwick, RI' },
    { value: 'West Greenwich, RI', label: 'West Greenwich, RI' },
    { value: 'West Warwick, RI', label: 'West Warwick, RI' },
    { value: 'Westerly, RI', label: 'Westerly, RI' },
    { value: 'Woonsocket, RI', label: 'Woonsocket, RI' }
];