export enum REBATE {
    PURCHASE_AMOUNT_BEV_FCEV = 1500,
    PURCHASE_AMOUNT_PHEV = 1000,
    LEASE_AMOUNT_BEV_FCEV = 1000,
    LEASE_AMOUNT_PHEV = 750,
    PLUS_PURCHASE_AMOUNT_BEV_FCEV = 1500,
    PLUS_PURCHASE_AMOUNT_PHEV = 1000,
    PLUS_LEASE_AMOUNT_BEV_FCEV = 1500,
    PLUS_LEASE_AMOUNT_PHEV = 750,
}